server:
  port: 8080

client:
  timeout:
    request: 3000
    connect: 500

spring:
  redis:
    host: localhost
    port: 6379

user:
  agents:
    file: src/main/resources/agents.txt

---

spring:
  config:
    activate:
      on-profile: docker
  redis:
    host: redis
    port: 6379

user:
  agents:
    file: /app/agents.txt