server:
  port: 8080

client:
  timeout:
    request: 3000
    connect: 500

spring:
  redis:
    host: localhost
    port: 6379

---

spring:
  config:
    activate:
      on-profile: docker
  redis:
    host: redis
    port: 6379